name: Deploy to EC2

on:
  push:
    branches:
    - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ENV_NAME: "Development"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fix file permissions
        run: |
          sudo chmod -R u+rwX .

      - name: SSH into EC2 and Prepare directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST_IP}}
          username: ${{secrets.EC2_USER_NAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            sudo mkdir -p /var/www/html/
            sudo chown -R ${{secrets.EC2_USERNAME}} /var/www/html/
            sudo chmod -R 755 /var/www/html/

      - name: Copy Code to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{secrets.EC2_HOST_IP}}
          username: ${{secrets.EC2_USER_NAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          source: "./*"
          target: /var/www/html/

      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{secrets.EC2_HOST_IP}}
          username: ${{secrets.EC2_USER_NAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          port: 22
          script: |
            sudo systemctl restart nginx


        
        


